### ISSUE TITLE
Let boxes actually flex?

### ISSUE THREAD

**Issue by irfaan** [yelled3/react-native-grid-example#2]
Do you know of a way we can let the boxes (e.g. row of 3) flex on their own automatically based on device screen width? It seems your method requires hard-coding the width of each element.

Any help would be much appreciated!
Thanks!

**Comment by yelled3** [comment]
@irfaan you can do what's been done in:
https://github.com/lucholaf/react-native-grid-view/blob/master/index.js#L34-L43

i.e, render a row (which takes the whole screen's width) and inside it place N items, each with `flex: 1`

hope it helps

**Comment by irfaan** [comment]
Thanks!
